import { useEffect, useRef } from 'react';
import type { RepoFeatures } from '@codetta/schema';
import { generateScore } from './music/generate';
import { barToTick, scoreDurationSeconds } from './music/score';
import { clipWindow } from './music/clip';
import { ticksAtSeconds } from './visuals/clock';
import { drawField } from './visuals/draw';
import { fieldFor } from './visuals/layout';
import { palettesFor } from './visuals/palette';
import { GALLERY } from './features/gallery';

/**
 * The picture a shared link unfurls with.
 *
 * Rendered by the real browser, through the same `drawField` the page and the video use, and
 * screenshotted at build time — see scripts/og.ts. That is the whole reason for doing it this
 * way rather than reimplementing the drawing in Go: an image generated by a second
 * implementation would differ from the site in ways nobody would notice until they saw both,
 * and the difference would be invisible in code review because both would look right alone.
 *
 * The frame it draws is the last one of the clip — the thirty seconds starting at the peak,
 * the same window the WAV and the video are cut from. A card is a still of the thing being
 * shared, and this is the only frame that is one.
 *
 * It was tick 0 first, on the argument that the card should show what the gallery tile shows
 * before anything plays. At tile size that reads as structure; at 1200x630 it is a dark
 * rectangle with a hairline across the top, because the whole legibility of this picture is
 * the contrast between the region that has been read and the region that has not, and at tick
 * 0 there is no read region at all. Two thirds of the way through, there is.
 */

/** What every platform crops to. Twice the size, so the card is sharp on a retina timeline. */
export const OG_WIDTH = 1200;
export const OG_HEIGHT = 630;

export function OgCard({ features }: { features: RepoFeatures }) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  // Resolved against the whole gallery, so the eight cards are as far apart in colour as the
  // eight tiles are. A card drawn from the repository alone could sit next to its neighbour
  // in someone's timeline wearing nearly the same hue.
  const seeds = GALLERY.map((entry) => entry.seed);
  const index = seeds.indexOf(features.seed);
  const palette = palettesFor(index >= 0 ? seeds : [...seeds, features.seed])[
    index >= 0 ? index : seeds.length
  ]!;

  useEffect(() => {
    const canvas = canvasRef.current;
    const context = canvas?.getContext('2d');
    if (!canvas || !context) return;

    const score = generateScore(features);
    const clip = clipWindow(score);
    const clipEnd = clip.startSeconds + clip.durationSeconds;

    drawField(
      context,
      OG_WIDTH,
      OG_HEIGHT,
      {
        columns: fieldFor(features),
        palette,
        fileCount: features.timeline.length,
        durationSeconds: scoreDurationSeconds(score),
        totalTicks: barToTick(score.bars),
      },
      { tick: ticksAtSeconds(clipEnd, score.bpm, barToTick(score.bars)), onsets: [], delta: 0 },
      new Map(),
    );

    // Read by the screenshot script, so it never captures a frame before the paint lands.
    canvas.dataset['ready'] = 'true';
  }, [features, palette]);

  return (
    <div
      style={{
        width: OG_WIDTH,
        height: OG_HEIGHT,
        position: 'relative',
        background: palette.ground,
      }}
    >
      <canvas ref={canvasRef} width={OG_WIDTH} height={OG_HEIGHT} data-og-canvas />
      <div
        style={{
          position: 'absolute',
          left: 56,
          bottom: 48,
          fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
          color: palette.modules[0],
        }}
      >
        <div
          style={{
            fontSize: 15,
            letterSpacing: '0.32em',
            textTransform: 'uppercase',
            opacity: 0.75,
          }}
        >
          Codetta
        </div>
        <div style={{ fontSize: 46, marginTop: 14, fontWeight: 500 }}>
          {features.repo.owner}/{features.repo.name}
        </div>
      </div>
    </div>
  );
}
