// Package site serves the built web app, and rewrites one block of its <head> when the
// request is a permalink.
//
// This is the only place in apps/api that produces anything a person reads, and it still
// holds no music knowledge: it reads a manifest of titles, descriptions and image paths that
// apps/web generated, and substitutes strings. The rule in CLAUDE.md is that music concepts
// never leak into this module, and a title that says "F Lydian at 120 BPM" would be one — so
// the sentence is written where the key is known and arrives here as text.
package site

import (
	"encoding/json"
	"fmt"
	"html"
	"io/fs"
	"net/http"
	"strings"
)

// Card is one repository's unfurl, as generated by apps/web's scripts/og.ts.
type Card struct {
	Owner       string `json:"owner"`
	Name        string `json:"name"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Image       string `json:"image"`
}

const (
	manifestPath = "og/manifest.json"
	indexPath    = "index.html"
	openTag      = "<!--og:start-->"
	closeTag     = "<!--og:end-->"
)

type Site struct {
	files http.Handler
	// The index split around the block to replace, so a request is two writes and a lookup
	// rather than a search through the document.
	head, tail string
	cards      map[string]Card
	// In the manifest's order, for Cards. The map above cannot answer that question.
	listed []Card
}

/*
Handler serves dist, with permalinks rendered.

Everything is read once, at construction, because all of it is build output: if the manifest
is missing or the index has lost its marker, that is a broken build and the right moment to
say so is startup. A permalink that silently unfurls as the generic card would otherwise look
fine to everyone except the person who shared it.
*/
func Handler(dist fs.FS) (*Site, error) {
	index, err := fs.ReadFile(dist, indexPath)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", indexPath, err)
	}

	document := string(index)
	open := strings.Index(document, openTag)
	end := strings.Index(document, closeTag)
	if open < 0 || end < open {
		return nil, fmt.Errorf("%s has no %s…%s block to replace", indexPath, openTag, closeTag)
	}

	raw, err := fs.ReadFile(dist, manifestPath)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", manifestPath, err)
	}

	var listed []Card
	if err := json.Unmarshal(raw, &listed); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", manifestPath, err)
	}

	cards := make(map[string]Card, len(listed))
	for _, card := range listed {
		cards[key(card.Owner, card.Name)] = card
	}

	return &Site{
		files:  http.FileServerFS(dist),
		head:   document[:open],
		tail:   document[end+len(closeTag):],
		cards:  cards,
		listed: listed,
	}, nil
}

/*
Cards lists the repositories this deployment's front page shows, in the manifest's order.

It exists so the cache warm has somewhere honest to get that list. The alternative was a
second list of eight repositories in Go, which would be right until the day the gallery
changed and nobody remembered — and this one is already in the image, already generated from
the gallery, and already read at boot.
*/
func (s *Site) Cards() []Card {
	return s.listed
}

// key folds case, because GitHub does: github.com/PSF/Requests is the same repository, and a
// link that unfurls differently depending on how someone typed it is a bug nobody can debug.
func key(owner, name string) string {
	return strings.ToLower(owner) + "/" + strings.ToLower(name)
}

func (s *Site) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	owner, name, ok := permalink(r.URL.Path)
	if !ok {
		s.files.ServeHTTP(w, r)
		return
	}

	// A repository with no pre-rendered card still gets its page — the app fetches it live —
	// and unfurls with the generic image. There are millions of repositories and eight cards;
	// the fallback is the normal case, not the failure case.
	card, known := s.cards[key(owner, name)]

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	// Short, because these are permalinks to a moving branch: the picture is of whatever HEAD
	// was when the card was made, and a day-long cache would outlive that quietly.
	w.Header().Set("Cache-Control", "public, max-age=300")

	if !known {
		_, _ = w.Write([]byte(s.head + defaultMeta + s.tail))
		return
	}

	_, _ = w.Write([]byte(s.head + meta(card) + s.tail))
}

// defaultMeta is what a page with no card of its own says. Deliberately not the index's own
// block: this handler owns what goes between the markers, and reconstructing it from the file
// would mean two answers to the same question.
const defaultMeta = `<meta property="og:title" content="Codetta" />` +
	`<meta property="og:description" content="Paste a GitHub repository. Hear what it sounds like." />` +
	`<meta property="og:image" content="/og/cover.png" />` +
	`<meta name="twitter:card" content="summary_large_image" />`

func meta(card Card) string {
	// Escaped because owner and name reach this through a URL. They are matched against the
	// manifest before they get here, so today nothing unescaped could arrive — but the escape
	// is what keeps that true if a future card is ever built from the request instead.
	return `<meta property="og:title" content="` + html.EscapeString(card.Title) + `" />` +
		`<meta property="og:description" content="` + html.EscapeString(card.Description) + `" />` +
		`<meta property="og:image" content="` + html.EscapeString(card.Image) + `" />` +
		`<meta name="twitter:card" content="summary_large_image" />`
}

// permalink recognises /r/{owner}/{name}, and nothing deeper. The shape is the web app's, in
// apps/web/src/features/route.ts; this only has to agree about which paths are pages.
func permalink(path string) (owner, name string, ok bool) {
	rest, found := strings.CutPrefix(path, "/r/")
	if !found {
		return "", "", false
	}

	owner, name, found = strings.Cut(strings.TrimSuffix(rest, "/"), "/")
	if !found || owner == "" || name == "" || strings.Contains(name, "/") {
		return "", "", false
	}

	return owner, name, true
}
